function Hd = untitled
%UNTITLED Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 11-Jan-2021 21:11:28

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 50000;  % Sampling Frequency

Fstop = 15;               % Stopband Frequency
Fpass = 700;              % Passband Frequency
Dstop = 0.92172785189;    % Stopband Attenuation
Dpass = 0.0033100189032;  % Passband Ripple
flag  = 'scale';          % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop Fpass]/(Fs/2), [0 1], [Dpass Dstop]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
