function Hd = highPassFilt
%HIGHPASSFILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 09-Aug-2020 03:07:53

% FIR Window Highpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 50000;  % Sampling Frequency

Fstop = 15;              % Stopband Frequency
Fpass = 700;             % Passband Frequency
Dstop = 0.70794578438;   % Stopband Attenuation
Dpass = 0.057501127785;  % Passband Ripple
flag  = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop Fpass]/(Fs/2), [0 1], [Dpass Dstop]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

%% Test section
% y = filter(Hd, x);
% figure;
% 
% tools.fftHandler(x,5e4);
% hold on
% tools.fftHandler(y,5e4);
% hold off

% [EOF]
